name: CI
on: [push, pull_request]

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      - name: Check style with prettier
        run: npm run format-check

      - name: Test
        run: npm run test

      - name: Check build
        run: npm run build

      - name: Run LiquidJS
        id: run-liquidjs
        uses: ./.
        with:
          variables: '{"hello": "Hello LiquidJS"}'
          template-string: "{{ hello }}"
          output-name: "rendered-result"
        
      - name: A/B Check
        if: ${{ steps.run-liquidjs.outputs.rendered-result != 'Hello LiquidJS' }} 
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed("A/B Check failed, 'steps.run-liquidjs.outputs.rendered-result' should be 'Hello LiquidJS'")
